### ISSUE TITLE
Javascript not loading correctly

### ISSUE THREAD

**Issue by heyrict** [pb10001/utakata-umigame#1]
Using script from googleapi.com would block my browser from loading anything '^'.

Maybe using scripts from cdnjs or cloudflare, or using packaging libraries such as webpack, browserify, or requirejs will work.

**Comment by pb10005** [comment]
In fact, yesterday I tried to block a spam which is detected by google analytics, 
and I'm afraid I blocked the wrong hostname.

Now I removed the filter. Does it work?

**Comment by heyrict** [comment]
Well, I mean, the GFW will block me from loading javascripts from google 😞 . Loading sources from other CDN or from different sources may make it work correctly. 

For example, I pass different links to requirejs to ensure that user can load scripts correctly in [Cindy v1.X](https://github.com/heyrict/cindy/blob/v1.6.1/sui_hei/static/main.js#L1)

**Comment by pb10005** [comment]
OK, I understand. I'll use cloudflare cdn instead. Thank you for reporting!
