### ISSUE TITLE
Code formatting

### ISSUE THREAD

**Issue by heyrict** [pb10001/utakata-umigame#2]
Consider automate code formatting with `eslint` and/or `prettier`.
Use a plugin like `ale` for `vim` to handle formatting on save.

> PS: `moment.js` is good, but its bundle size may be large (about 300KB minified) for too many language files (each ~3KB).

**Comment by pb10005** [comment]
Thank you for your suggestion.
I tried formatting on save by prettier(with atom) just now and found it useful.

I've not decided to employ `moment.js` yet. JavaScript `Date` is enough for now.

**Comment by heyrict** [comment]
Close this issue for the advice is taken :smiley:
